<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['admin_form_config_loaded'] = true;

$config['form_login_config'] = [
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'category' => 'base',
		'type' => 'hidden',
		'default' => 'USR001',
		'list' => false,
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'base',
		'type' => 'text',
		'icon' => 'ri-user-line',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'base',
		'type' => 'password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
	],
    [
        'field' => 'autologin',
        'label' => 'lang:auth.autologin',
        'rules' => '',
        'errors' => [],
        'category' => 'base',
        'type' => 'checkbox',
        'subtype' => 'single',
        'attributes' => [],
        'form_attributes' => [],
    ],
];

$config['form_find_id_config'] = [
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'category' => 'base',
		'type' => 'hidden',
		'default' => 'USR001',
		'list' => false,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'category' => 'base',
		'type' => 'email',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User Email',
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'base',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];

$config['form_find_password_config'] = [
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'category' => 'base',
		'type' => 'hidden',
		'default' => 'USR001',
		'list' => false,
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required',
		'category' => 'base',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required',
		'category' => 'base',
		'type' => 'email',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User Email',
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'base',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];

$config['form_administrators_config'] = [
    [
        'field' => 'user_id',
        'label' => 'lang:user.user_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'subtype' => 'identifier',
        'list' => false,
    ],
    [
        'field' => 'id',
        'label' => 'lang:user.id',
        'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
        'form' => true,
        'errors' => [],
        'category' => 'custom',
        'type' => 'text',
        'subtype' => 'unique',
        'icon' => 'ri-user-line',
        'form_text' => 'Please enter at least 4 characters',
        'attributes' => [
            'autocapitalize' => 'none',
            'autocomplete' => 'off',
            'placeholder' => 'Enter The User ID',
        ],
        'form_attributes' => [
            'detect_changed' => true,
            'editable' => false,
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"id", "title":"아이디"}',
            'text_type' => 'eng|num',
        ],
        'list' => true,
    ],
    [
        'field' => 'password',
        'label' => 'lang:user.password',
        'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
        'form' => true,
        'errors' => [],
        'category' => 'group',
        'type' => 'password',
        'icon' => 'svg:ri-lock-password-line',
        'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
        'attributes' => [
            'autocomplete' => 'new-password',
            'placeholder' => 'Password Dots',
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
        'group' => 'user_password',
        'group_attributes' => [
            'envelope_name' => false,
            'label' => 'lang:user.password',
            'form_text' => '',
            'type' => 'new_password',
            'key' => 'password',
        ],
        'list' => false,
    ],
    [
        'field' => 'password_confirm',
        'label' => 'lang:user.password_confirm',
        'rules' => 'trim|required_mod[add]|password_matches[password]',
        'form' => true,
        'errors' => [],
        'category' => 'group',
        'type' => 'password',
        'subtype' => 'password_confirm',
        'icon' => 'svg:ri-lock-password-fill',
        'form_text' => 'Please Repeat The Password',
        'attributes' => [
            'autocomplete' => 'new-password',
            'placeholder' => 'Password Dots',
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
        'group' => 'user_password',
        'group_attributes' => [
            'key' => 'password_confirm',
        ],
        'list' => false,
    ],
    [
        'field' => 'name',
        'label' => 'lang:user.name',
        'rules' => 'trim|required',
        'form' => true,
        'list' => true,
    ],
    [
        'field' => 'email',
        'label' => 'lang:user.email',
        'rules' => 'trim|required|is_unique[user.email.user_id]',
        'form' => true,
        'category' => 'custom',
        'type' => 'text',
        'subtype' => 'unique',
        'icon' => 'ri-font-family',
        'attributes' => [
            'placeholder' => 'Enter The User Email',
        ],
        'form_attributes' => [
            'editable' => false,
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"email", "title":"이메일"}',
            'text_type' => 'email',
        ],
        'list' => true,
    ],
    [
        'field' => 'tel',
        'label' => 'lang:user.tel',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'tel',
        'subtype' => 'cleave-hp',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'recent_dt',
        'label' => 'lang:common.recent_dt',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => 'ri-calendar-line',
        'form_text' => '',
        'attributes' => [
            'placeholder' => 'YYYY-MM-DD',
        ],
        'form_attributes' => [
            'view_mod' => 'edit',
        ],
        'list' => true,
    ],
];

$config['form_company_config'] = [
    [
        'field' => 'comp_id',
        'label' => 'lang:comp.comp_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'subtype' => 'identifier',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_cd',
        'label' => 'lang:comp.comp_cd',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => 'COM002',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_code',
        'label' => 'lang:company.comp_code',
        'form' => true,
        'rules' => 'trim|required|exact_length[6]|integer|is_unique[company.comp_code.comp_id]',
        'errors' => [],
        'category' => 'custom',
        'type' => 'text',
        'subtype' => 'unique',
        'icon' => 'ri-number-2',
        'form_text' => 'Enter The 6-digit Code With Numbers',
        'attributes' => [],
        'form_attributes' => [
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"comp_code", "title":"회사 코드"}',
            'text_type' => 'num',
        ],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_name',
        'label' => 'lang:company.comp_name',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_ceo',
        'label' => 'lang:company.comp_ceo',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_tel',
        'label' => 'lang:company.comp_tel',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'tel',
        'subtype' => 'cleave-hp',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_address',
        'label' => 'lang:company.comp_address',
        'form' => false,
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_zipcode',
        'label' => 'lang:company.comp_zipcode',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'group',
        'type' => 'text',
        'subtype' => 'zipcode',
        'icon' => null,
        'form_text' => '',
        'attributes' => [
            'readonly' => 'readonly',
            'placeholder' => 'Search The Address',
        ],
        'form_attributes' => [
            'with_btn' => true,
            'btn_type' => 'addr_daum',
        ],
        'group' => 'comp_addr',
        'group_attributes' => [
            'envelope_name' => false,
            'label' => 'lang:company.comp_addr',
            'form_text' => '',
            'type' => 'addr_daum',
            'key' => 'zipcode',
        ],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_addr1',
        'label' => 'lang:company.comp_addr1',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'group',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => null,
        'form_text' => '',
        'attributes' => [
            'readonly' => 'readonly',
            'placeholder' => 'Search The Address',
        ],
        'group_attributes' => [
            'key' => 'addr1',
        ],
        'group' => 'comp_addr',
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_addr2',
        'label' => 'lang:company.comp_addr2',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'group',
        'type' => 'text',
        'icon' => null,
        'form_text' => '',
        'attributes' => [
            'placeholder' => 'Enter The Extra Address',
        ],
        'group' => 'comp_addr',
        'group_attributes' => [
            'key' => 'addr2',
        ],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_memo',
        'label' => 'lang:company.comp_memo',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'textarea',
        'subtype' => 'autosize',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'created_id',
        'label' => 'lang:common.created_id',
        'form' => false,
        'list' => true,
    ],
    [
        'field' => 'recent_dt',
        'label' => 'lang:common.recent_dt',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => 'ri-calendar-line',
        'form_text' => '',
        'attributes' => [
            'placeholder' => 'YYYY-MM-DD',
        ],
        'form_attributes' => [
            'view_mod' => 'edit',
        ],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
];

$config['form_myinfo_config'] = [
	[
		'field' => 'user_id',
		'label' => 'lang:user.user_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'errors' => [],
		'type' => 'hidden',
		'subtype' => 'identifier',
	],
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'USR002',
	],
	[
		'field' => 'del_yn',
		'label' => 'lang:user.del_yn',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'N',
	],
	[
		'field' => 'withdraw_yn',
		'label' => 'lang:user.withdraw_yn',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'N',
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
		'form' => true,
		'errors' => [],
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-user-line',
		'form_text' => 'Please enter at least 4 characters',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => false,
		],
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'icon' => 'svg:ri-lock-password-line',
		'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'envelope_name' => false,
			'label' => 'lang:user.password',
			'form_text' => '',
			'type' => 'new_password',
			'key' => 'password',
		],
	],
	[
		'field' => 'password_confirm',
		'label' => 'lang:user.password_confirm',
		'rules' => 'trim|required_mod[add]|password_matches[password]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'subtype' => 'password_confirm',
		'icon' => 'svg:ri-lock-password-fill',
		'form_text' => 'Please Repeat The Password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'key' => 'password_confirm',
		],
	],
	[
		'field' => 'name',
		'label' => 'lang:user.name',
		'rules' => 'trim|required',
		'form' => true,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'form' => true,
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-font-family',
		'attributes' => [
			'placeholder' => 'Enter The User Email',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => false,
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list_attributes' => [],
	],
];

$config['form_project_config'] = [
    [
        'field' => 'project_id',
        'label' => 'lang:project.project_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'type' => 'hidden',
        'subtype' => 'identifier',
    ],
    [
        'field' => 'project_name',
        'rules' => 'required_mod[edit]',
    ],
    [
        'field' => 'start_dt',
        'rules' => 'required_mod[edit]',
        'type' => 'tel',
        'subtype' => 'cleave-fulldate',
        'icon' => 'ri-calendar-line',
    ],
    [
        'field' => 'end_dt',
        'rules' => 'required_mod[edit]',
        'type' => 'tel',
        'subtype' => 'cleave-fulldate',
        'icon' => 'ri-calendar-line',
    ],
    [
        'field' => 'comp_id',
        'rules' => 'required_mod[edit]',
        'type' => 'select',
        'subtype' => 'select2',
        'attributes' => [
            'placeholder' => 'Select The Company',
        ],
        'option_attributes' => [
            'option_type' => 'model',
            'option_data' => [
                'model' => 'Model_Company',
                'method' => 'getList',
                'params' => [
                ],
            ],
            'render' => [
                'id' => 'comp_id',
                'text' => 'comp_name',
            ],
        ],
    ],
];
