<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['admin_form_config_loaded'] = true;

$config['form_administrators_config'] = [
    [
        'field' => 'administrator_id',
        'label' => 'lang:administrator.administrator_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'subtype' => 'identifier',
        'list' => false,
    ],
    [
        'field' => 'user_id',
        'label' => 'lang:user.user_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'list' => false,
    ],
    [
        'field' => 'user_cd',
        'label' => 'lang:user.user_cd',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'default' => 'USR001',
        'list' => false,
    ],
    [
        'field' => 'id',
        'label' => 'lang:user.id',
        'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
        'form' => true,
        'errors' => [],
        'type' => 'custom',
        'subtype' => 'unique',
        'icon' => 'ri-user-line',
        'form_text' => 'Please enter at least 4 characters',
        'attributes' => [
            'autocapitalize' => 'none',
            'autocomplete' => 'off',
            'placeholder' => 'Enter The User ID',
        ],
        'form_attributes' => [
            'detect_changed' => true,
            'editable' => false,
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"id", "title":"아이디"}',
            'text_type' => 'eng|num',
        ],
    ],
    [
        'field' => 'password',
        'label' => 'lang:user.password',
        'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
        'form' => true,
        'errors' => [],
        'category' => 'group',
        'type' => 'password',
        'icon' => 'svg:ri-lock-password-line',
        'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
        'attributes' => [
            'autocomplete' => 'new-password',
            'placeholder' => 'Password Dots',
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
        'group' => 'user_password',
        'group_attributes' => [
            'envelope_name' => false,
            'label' => 'lang:user.password',
            'form_text' => '',
            'type' => 'new_password',
            'key' => 'password',
        ],
        'list' => false,
    ],
    [
        'field' => 'password_confirm',
        'label' => 'lang:user.password_confirm',
        'rules' => 'trim|required_mod[add]|password_matches[password]',
        'form' => true,
        'errors' => [],
        'category' => 'group',
        'type' => 'password',
        'subtype' => 'password_confirm',
        'icon' => 'svg:ri-lock-password-fill',
        'form_text' => 'Please Repeat The Password',
        'attributes' => [
            'autocomplete' => 'new-password',
            'placeholder' => 'Password Dots',
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
        'group' => 'user_password',
        'group_attributes' => [
            'key' => 'password_confirm',
        ],
        'list' => false,
    ],
    [
        'field' => 'name',
        'label' => 'lang:user.name',
        'rules' => 'trim|required',
        'form' => true,
    ],
    [
        'field' => 'email',
        'label' => 'lang:user.email',
        'rules' => 'trim|is_unique[user.email.user_id]',
        'form' => true,
        'type' => 'custom',
        'subtype' => 'unique',
        'icon' => 'ri-font-family',
        'attributes' => [
            'placeholder' => 'Enter The User Email',
        ],
        'form_attributes' => [
            'editable' => false,
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"email", "title":"이메일"}',
            'text_type' => 'email',
        ],
    ],
    [
        'field' => 'tel',
        'label' => 'lang:user.tel',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'tel',
        'subtype' => 'cleave-hp',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'user_api_key',
        'label' => 'lang:user.user_api_key',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => 'ri-key-2-line',
        'attributes' => [
            'clipboard' => true,
        ],
        'form_attributes' => [
            'editable' => false,
            'view_mod' => 'edit',
        ],
        'list' => false,
    ],
    [
        'field' => 'recent_dt',
        'label' => 'lang:common.recent_dt',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => 'ri-calendar-line',
        'form_text' => '',
        'attributes' => [
            'placeholder' => 'YYYY-MM-DD',
        ],
        'form_attributes' => [
            'view_mod' => 'edit',
        ],
        'list' => true,
    ],
];

$config['form_partners_config'] = [
    [
        'field' => 'partner_id',
        'label' => 'lang:partner.partner_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'subtype' => 'identifier',
        'list' => false,
    ],
    [
        'field' => 'user_id',
        'label' => 'lang:user.user_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'list' => false,
    ],
    [
        'field' => 'user_cd',
        'label' => 'lang:user.user_cd',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'default' => 'USR002',
        'list' => false,
    ],
    [
        'field' => 'id',
        'label' => 'lang:user.id',
        'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
        'form' => true,
        'errors' => [],
        'type' => 'custom',
        'subtype' => 'unique',
        'icon' => 'ri-user-line',
        'form_text' => 'Please enter at least 4 characters',
        'attributes' => [
            'autocapitalize' => 'none',
            'autocomplete' => 'off',
            'placeholder' => 'Enter The User ID',
        ],
        'form_attributes' => [
            'detect_changed' => true,
            'editable' => false,
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"id", "title":"아이디"}',
            'text_type' => 'eng|num',
        ],
    ],
    [
        'field' => 'password',
        'label' => 'lang:user.password',
        'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
        'form' => true,
        'errors' => [],
        'category' => 'group',
        'type' => 'password',
        'icon' => 'svg:ri-lock-password-line',
        'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
        'attributes' => [
            'autocomplete' => 'new-password',
            'placeholder' => 'Password Dots',
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
        'group' => 'user_password',
        'group_attributes' => [
            'envelope_name' => false,
            'label' => 'lang:user.password',
            'form_text' => '',
            'type' => 'new_password',
            'key' => 'password',
        ],
        'list' => false,
    ],
    [
        'field' => 'password_confirm',
        'label' => 'lang:user.password_confirm',
        'rules' => 'trim|required_mod[add]|password_matches[password]',
        'form' => true,
        'errors' => [],
        'category' => 'group',
        'type' => 'password',
        'subtype' => 'password_confirm',
        'icon' => 'svg:ri-lock-password-fill',
        'form_text' => 'Please Repeat The Password',
        'attributes' => [
            'autocomplete' => 'new-password',
            'placeholder' => 'Password Dots',
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
        'group' => 'user_password',
        'group_attributes' => [
            'key' => 'password_confirm',
        ],
        'list' => false,
    ],
    [
        'field' => 'name',
        'label' => 'lang:user.name',
        'rules' => 'trim|required',
        'form' => true,
    ],
    [
        'field' => 'email',
        'label' => 'lang:user.email',
        'rules' => 'trim|is_unique[user.email.user_id]',
        'form' => true,
        'type' => 'custom',
        'subtype' => 'unique',
        'icon' => 'ri-font-family',
        'attributes' => [
            'placeholder' => 'Enter The User Email',
        ],
        'form_attributes' => [
            'editable' => false,
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"email", "title":"이메일"}',
            'text_type' => 'email',
        ],
    ],
    [
        'field' => 'tel',
        'label' => 'lang:user.tel',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'tel',
        'subtype' => 'cleave-hp',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list_attributes' => [],
    ],
    [
        'field' => 'company_ids',
        'label' => 'lang:partner.company_ids',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'select',
        'subtype' => 'select2',
        'icon' => null,
        'form_text' => '',
        'attributes' => [
            'multiple' => true,
        ],
        'option_attributes' => [
            'option_type' => 'model',
            'option_data' => [
                'model' => 'Model_Company',
                'method' => 'getList',
                'params' => [],
            ],
            'render' => [
                'id' => 'company_id',
                'text' => 'company_name',
            ],
        ],
        'default' => '',
        'list_attributes' => [],
    ],
    [
        'field' => 'user_api_key',
        'label' => 'lang:user.user_api_key',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => 'ri-key-2-line',
        'attributes' => [
            'clipboard' => true,
        ],
        'form_attributes' => [
            'editable' => false,
            'view_mod' => 'edit',
        ],
        'list' => false,
    ],
    [
        'field' => 'recent_dt',
        'label' => 'lang:common.recent_dt',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => 'ri-calendar-line',
        'form_text' => '',
        'attributes' => [
            'placeholder' => 'YYYY-MM-DD',
        ],
        'form_attributes' => [
            'view_mod' => 'edit',
        ],
    ],
];

$config['form_company_config'] = [
    [
        'field' => 'comp_id',
        'label' => 'lang:comp.comp_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'subtype' => 'identifier',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_cd',
        'label' => 'lang:comp.comp_cd',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => 'COM002',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_code',
        'label' => 'lang:company.comp_code',
        'form' => true,
        'rules' => 'trim|required|exact_length[6]|integer|is_unique[company.comp_code.comp_id]',
        'errors' => [],
        'type' => 'custom',
        'subtype' => 'unique',
        'icon' => 'ri-number-2',
        'form_text' => 'Enter The 6-digit Code With Numbers',
        'attributes' => [],
        'form_attributes' => [
            'with_btn' => true,
            'btn_type' => 'dup_check',
            'btn_params' => '{"key":"comp_code", "title":"회사 코드"}',
            'text_type' => 'num',
        ],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_name',
        'label' => 'lang:company.comp_name',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_ceo',
        'label' => 'lang:company.comp_ceo',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_tel',
        'label' => 'lang:company.comp_tel',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'tel',
        'subtype' => 'cleave-hp',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_address',
        'label' => 'lang:company.comp_address',
        'form' => false,
        'list' => true,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_zipcode',
        'label' => 'lang:company.comp_zipcode',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'group',
        'type' => 'text',
        'subtype' => 'zipcode',
        'icon' => null,
        'form_text' => '',
        'attributes' => [
            'readonly' => 'readonly',
            'placeholder' => 'Search The Address',
        ],
        'form_attributes' => [
            'with_btn' => true,
            'btn_type' => 'addr_daum',
        ],
        'group' => 'comp_addr',
        'group_attributes' => [
            'envelope_name' => false,
            'label' => 'lang:company.comp_addr',
            'form_text' => '',
            'type' => 'addr_daum',
            'key' => 'zipcode',
        ],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_addr1',
        'label' => 'lang:company.comp_addr1',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'group',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => null,
        'form_text' => '',
        'attributes' => [
            'readonly' => 'readonly',
            'placeholder' => 'Search The Address',
        ],
        'group_attributes' => [
            'key' => 'addr1',
        ],
        'group' => 'comp_addr',
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_addr2',
        'label' => 'lang:company.comp_addr2',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'group',
        'type' => 'text',
        'icon' => null,
        'form_text' => '',
        'attributes' => [
            'placeholder' => 'Enter The Extra Address',
        ],
        'group' => 'comp_addr',
        'group_attributes' => [
            'key' => 'addr2',
        ],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'comp_memo',
        'label' => 'lang:company.comp_memo',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'textarea',
        'subtype' => 'autosize',
        'icon' => null,
        'form_text' => '',
        'attributes' => [],
        'default' => '',
        'list' => false,
        'list_attributes' => [],
    ],
    [
        'field' => 'created_id',
        'label' => 'lang:common.created_id',
        'form' => false,
        'list' => true,
    ],
    [
        'field' => 'recent_dt',
        'label' => 'lang:common.recent_dt',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'subtype' => 'readonly',
        'icon' => 'ri-calendar-line',
        'form_text' => '',
        'attributes' => [
            'placeholder' => 'YYYY-MM-DD',
        ],
        'form_attributes' => [
            'view_mod' => 'edit',
        ],
        'default' => '',
        'list' => true,
        'list_attributes' => [],
    ],
];

$config['form_categories_config'] = [
    [
        'field' => 'category_id',
        'label' => 'lang:category.category_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'subtype' => 'identifier',
        'icon' => null,
    ],
    [
        'field' => 'depth',
        'label' => 'lang:category.depth',
        'form' => true,
        'rules' => 'trim|required|min[1]|max[3]',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'default' => 1,
    ],
    [
        'field' => 'parent_id',
        'label' => 'lang:category.parent_id',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'hidden',
        'default' => 0,
    ],
    [
        'field' => 'category_name',
        'label' => 'lang:category.category_name',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'icon' => null,
    ],
    [
        'field' => 'category_nick',
        'label' => 'lang:category.category_nick',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'icon' => null,
    ],
    [
        'field' => 'category_alias',
        'label' => 'lang:category.category_alias',
        'form' => true,
        'rules' => 'trim',
        'errors' => [],
        'category' => 'base',
        'type' => 'text',
        'icon' => null,
    ],
//    [
//        'field' => 'category_icon',
//        'label' => 'lang:common.category_icon',
//        'form' => true,
//        'rules' => 'trim|dropzone_required',
//        'errors' => [],
//        'category' => 'base',
//        'type' => 'file',
//        'subtype' => 'dropzone',
//        'form_text' => [
//            'line' => 'Drop files here or click to upload',
//            'replace' => 'IMG',
//            'icon' => 'ri-file-image-fill',
//            'icon_size' => 16,
//        ],
//        'attributes' => [
//            'style' => 'base',
//            'max' => 1,
//            'multiple' => 'false',
//        ],
//    ],
    [
        'field' => 'category_icon',
        'label' => 'lang:category.category_icon',
        'form' => true,
        'rules' => 'trim|required_if_empty_file[category_icon|category.category_icon.category_id]',
        'errors' => [],
        'category' => 'base',
        'type' => 'file',
        'subtype' => 'thumbnail',
        'icon' => 'ri-file-image-line',
        'form_text' => [
            'line' => 'Upload File Only',
            'replace' => 'IMG',
            'icon' => 'ri-file-image-fill',
            'icon_size' => 16,
        ],
        'attributes' => [
            'max' => 1,
            'accept' => 'image/jpeg,image/png',
            'multiple' => 'false',
        ],
        'form_attributes' => [
            'with_list' => true,
            'list_delete' => 'thumbnail',
        ],
        'list' => true,
        'list_attributes' => [
            'format' => 'img',
            'icon' => 'ri-image-fill',
            'onclick' => [
                'kind' => 'bs',
                'attrs' => [
                    'toggle' => 'popover',
                    'trigger' => 'hover',
                    'placement' => 'right',
                    'html' => 'true',
                    'template' => '<div class="popover" role="tooltip"><div class="popover-arrow"></div><div class="popover-body p-0 rounded-3 overflow-hidden"></div></div>',
                ]
            ],
            'render' => []
        ]
    ],
    [
        'field' => 'category_srt',
        'label' => 'lang:category.category_srt',
        'form' => true,
        'rules' => 'trim|required_mod[add]|min[1]|numeric',
        'errors' => [],
        'category' => 'base',
        'type' => 'base',
        'subtype' => 'number',
        'icon' => null,
        'form_attributes' => [
            'detect_changed' => true,
        ],
    ],
    [
        'field' => 'use_yn',
        'label' => 'lang:common.use_yn',
        'form' => true,
        'rules' => 'trim|required',
        'errors' => [],
        'category' => 'base',
        'type' => 'select',
        'subtype' => 'selectpicker',
        'icon' => null,
        'option_attributes' => [
            'option_type' => 'yn',
        ],
    ],
];

$config['form_myinfo_config'] = [
	[
		'field' => 'user_id',
		'label' => 'lang:user.user_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'errors' => [],
		'type' => 'hidden',
		'subtype' => 'identifier',
	],
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'USR002',
	],
	[
		'field' => 'del_yn',
		'label' => 'lang:user.del_yn',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'N',
	],
	[
		'field' => 'withdraw_yn',
		'label' => 'lang:user.withdraw_yn',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'N',
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
		'form' => true,
		'errors' => [],
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-user-line',
		'form_text' => 'Please enter at least 4 characters',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => false,
		],
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'icon' => 'svg:ri-lock-password-line',
		'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'envelope_name' => false,
			'label' => 'lang:user.password',
			'form_text' => '',
			'type' => 'new_password',
			'key' => 'password',
		],
	],
	[
		'field' => 'password_confirm',
		'label' => 'lang:user.password_confirm',
		'rules' => 'trim|required_mod[add]|password_matches[password]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'subtype' => 'password_confirm',
		'icon' => 'svg:ri-lock-password-fill',
		'form_text' => 'Please Repeat The Password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'key' => 'password_confirm',
		],
	],
	[
		'field' => 'name',
		'label' => 'lang:user.name',
		'rules' => 'trim|required',
		'form' => true,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'form' => true,
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-font-family',
		'attributes' => [
			'placeholder' => 'Enter The User Email',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => false,
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list_attributes' => [],
	],
];

$config['form_project_config'] = [
    [
        'field' => 'project_id',
        'label' => 'lang:project.project_id',
        'form' => true,
        'rules' => 'trim|required_mod[edit]',
        'errors' => [],
        'type' => 'hidden',
        'subtype' => 'identifier',
    ],
    [
        'field' => 'project_name',
        'rules' => 'required_mod[edit]',
    ],
    [
        'field' => 'start_dt',
        'rules' => 'required_mod[edit]',
        'type' => 'tel',
        'subtype' => 'cleave-fulldate',
        'icon' => 'ri-calendar-line',
    ],
    [
        'field' => 'end_dt',
        'rules' => 'required_mod[edit]',
        'type' => 'tel',
        'subtype' => 'cleave-fulldate',
        'icon' => 'ri-calendar-line',
    ],
    [
        'field' => 'comp_id',
        'rules' => 'required_mod[edit]',
        'type' => 'select',
        'subtype' => 'select2',
        'attributes' => [
            'placeholder' => 'Select The Company',
        ],
        'option_attributes' => [
            'option_type' => 'model',
            'option_data' => [
                'model' => 'Model_Company',
                'method' => 'getList',
                'params' => [
                ],
            ],
            'render' => [
                'id' => 'comp_id',
                'text' => 'comp_name',
            ],
        ],
    ],
];
