<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class Administrators extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Model_User', 'Model');
//		$this->load->model('Model_Administrator', 'Model');
//		$this->load->model('Model_User', 'Model_Parent');

        $this->setProperties($this->Model);

        $this->defaultList = [
            'user_cd' => 'USR001',
            'use_yn' => 'Y',
            'del_yn' => 'N',
            'approve_yn' => 'Y',
            'withdraw_yn' => 'N',
        ];
    }

    public function beforeDelete($key = 0): array
    {
        $remains = $this->Model->getCnt([
            'where' => [
                'user_cd' => 'USR001'
            ],
            'whereNot' => [
                'user_id' => $key
            ],
        ]);

        if(!$remains) {
            $this->response([
                'code' => NO_REMAIN_ADMINS,
            ]);
        }

        return parent::beforeDelete($key); // TODO: Change the autogenerated stub
    }
}
