<?php defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class ArticleRead extends Common
{
	function __construct()
	{
		parent::__construct();

		$this->load->model('Model_Article_Read', 'Model');
		$this->load->model('Model_Article');
		$this->load->model('Model_User');

		$this->setProperties($this->Model);
	}

	protected function beforePut($key, $model = null)
	{
		$tokenData = $this->validateToken();

		$dto = parent::beforePut($key, $model); // TODO: Change the autogenerated stub

		$dto['user_id'] = $tokenData->user_id;
		$dto['read_dt'] = date('Y-m-d H:i:s');

		$readData = $this->Model->getData([], $dto);
		if($readData) {
			$read_dt = $readData->read_dt;
			if(time() >= strtotime($read_dt) + 60*60){
				$this->Model_Article->modNumb('view_count', 1, [
					'article_id' => $dto['article_id'],
				]);

				return $dto;
			}else{
				$this->response([
					'code' => DATA_PROCESSED,
				]);
			}
		}else{
			$this->Model_Article->modNumb('view_count', 1, [
				'article_id' => $dto['article_id'],
			]);

			return $dto;
		}
	}

}
