<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class Categories extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->routeTitle = '카테고리';

        $this->validateModel('Model_Category', 'Model');

        $this->setProperties($this->Model);

        $this->defaultList = [
            'depth' => 1,
        ];

        $this->fileList = [
            'category_icon'
        ];

        $this->methods['list_post'] = [
            'key' => false,
            'log' => false,
        ];
    }

    protected function beforeList($data): array
    {
        $data = parent::beforeList($data);
        $data['orderBy'] = ['category_srt' => 'ASC'];
        return $data;
    }

    protected function beforePost($key = 0, $model = null): array
    {
        list($key, $data) = parent::beforePost($key);

        if($data['use_yn'] === 'N') $data['category_srt'] = 0;

        return [$key, $data];
    }

    protected function executeAdd($dto, $bool, $model = null): array
    {
        if($dto['category_srt'] === 0) {
            return parent::executeAdd($dto, $bool, $model); // TODO: Change the autogenerated stub
        }else{
            $dto = parent::executeAdd($dto, $bool, $model);
            $this->reorderList('category_srt', 'category_id', 'parent_id', [
                'where' => ['use_yn' => 'Y']
            ], $dto);
            return $dto;
        }
    }

    protected function executeModify($key, $dto, $bool, $model = null): array
    {
        $original = $this->Model->getData([], [
            'where' => ['category_id' => $dto['category_id']],
        ]);

        if(!array_key_exists('category_srt', $dto) || (int)$dto['category_srt'] === (int)$original->category_srt) {
            return parent::executeModify($key, $dto, $bool, $model); // TODO: Change the autogenerated stub
        }else{
            $dto = parent::executeModify($key, $dto, $bool, $model);
            $this->reorderList('category_srt', 'category_id', 'parent_id', [
                'where' => ['use_yn' => 'Y']
            ], $dto);
            return $dto;
        }
    }

    protected function executeRemove($key, $data, $bool): array
    {
        $data = parent::executeRemove($key, $data, $bool);

        $this->reorderList('category_srt', 'category_id', 'parent_id', [
            'where' => ['parent_id' => $data['parent_id'], 'use_yn' => 'Y'],
            'whereNot' => ['sml_cd' => '000']
        ]);

        return $data;
    }
}
