<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class Logs extends Common
{
    function __construct()
    {
        parent::__construct();

        log_message("info", "Informational Message");

        $this->noIndexMethod = true;
    }

    public function userAccess_get()
    {
        $this->validateModel('Model_User_Logs', 'Model');

        $this->routeTitle = '사용자 로그';

        $this->handleGet();
    }

    protected function beforeList($data): array
    {
        $data['filter']['whereNot'] = [
            'user.user_cd' => ['USR000']
        ];

        return parent::beforeList($data);
    }

    public function transformView($data): object
    {
        switch ($data->type) {
            case 'auth' :
                $data->flag = 'info';
                break;
            case 'read' :
                $data->flag = 'secondary';
                break;
            case 'create' :
                $data->flag = 'primary';
                break;
            case 'update' :
                $data->flag = 'warning';
                break;
            case 'delete' :
                $data->flag = 'danger';
                break;
        }

        if(date('Y-m-d', strtotime($data->datetime)) == date('Y-m-d')) {
            $data->time = get_time_taken_as_string($data->datetime);
        }else{
            $data->time = date('H:i:s', strtotime($data->datetime));
        }

        return parent::transformView($data); // TODO: Change the autogenerated stub
    }

    public function errors_get()
    {
        $this->routeTitle = '에러 로그';

        $pageNo = $this->input->get('pageNo') ?? 0;
        $limit = $this->input->get('limit') ?? 10;
        $filters = $this->input->get('filters') ?? [];

        $date = $filters['date']['on_date'] ? : date('Y-m-d');
        $logThreshold = $filters['whereIn']['log_threshold'] ?? [];
        $keyword = $filters['like'][0]['value'] ?? '';
        $isToday = $date === date('Y-m-d');

        $logPath = !empty($this->config->item('log_path'))
            ? rtrim($this->config->item('log_path'), '/\\').DIRECTORY_SEPARATOR
            : APPPATH.'logs'.DIRECTORY_SEPARATOR
        ;

        $logFilename = !empty($this->config->item('log_filename'))
            ? $this->config->item('log_filename')
            : 'log-'.$date.'.php';

        $items = [];
        $allResult = [];
        $filteredResult = [];

        if(file_exists($logPath.$logFilename)) {
            $content = file_get_contents($logPath.$logFilename);
            $lines = array_reverse(split_log_lines($content));

            foreach ($lines as $line) {
                $item = parse_log_line($line);

                if($keyword) {
                    if(!str_contains($item['message'], $keyword)) continue;
                }

                if ($isToday) {
                    $item['time'] = get_time_taken_as_string($item['datetime']);
                } else {
                    $item['time'] = date('H:i:s', strtotime($item['datetime']));
                }

                switch ($item['level']) {
                    case 'ERROR' :
                        $item['flag'] = 'danger';
                        break;
                    case 'DEBUG' :
                        $item['flag'] = 'warning';
                        break;
                    case 'INFO' :
                        $item['flag'] = 'info';
                        break;
                }
                $item['display'] = 'd-none';

                $allResult[] = $item;
            }

            if(empty($logThreshold)) {
                $filteredResult = $allResult;
            }else{
                $filteredResult = array_filter($allResult, function($item) use ($logThreshold) {
                    return in_array($item['level'], $logThreshold);
                });
            }

            $items = array_slice($filteredResult, $pageNo * $limit, $limit);
        }

        $this->loggingUserlog();

        $this->response([
            'code' => DATA_RETRIEVED,
            'data' => $items,
            'extra' => [
                'draw' => $this->input->get('draw') ?? 0,
                'recordsTotal' => count($allResult),
                'recordsFiltered' => count($filteredResult),
            ],
        ]);
    }
}
