<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class MenuAuth extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Model_Menu_Auth', 'Model');
        $this->load->model('Model_Menu');

        $this->setProperties($this->Model);

        if($this->flag !== 'admin') show_404();
    }

    protected function beforeGet($key = 0): array
    {
        list($key, $data) = parent::beforeGet($key); // TODO: Change the autogenerated stub

        $data['join'] = [
            'select' => '*',
            'table' => 'menu',
            'matches' => [
                'menu_id' => 'menu_id'
            ],
            'direction' => 'left'
        ];

        return [$key, $data];
    }

    protected function beforeList($data): array
    {
        if(!$this->Model->getCnt($data)){
            $menuList = $this->Model_Menu->getList([], [
                'where' => [
                    'is_super' => 0,
                    'is_auth' => 1,
                    'is_use' => 1,
                ],
                'orderBy' => [
                    'depth' => 'asc',
                    'srt' => 'asc',
                ]
            ]);
            foreach ($menuList as $item) {
                $this->Model->addData(array_merge($data['where'], [
                    'menu_id' => $item->menu_id,
                    'menu_auth' => '0000',
                    'scope_cd' => 'SCP001',
                ]));
            }
        }

        return parent::beforeList($data);
    }

    protected function transformView($data): object
    {
        $data->title = lang('nav.'.$data->title);
        if($data->depth > 1) {
            $data->title = str_repeat('&nbsp;', ($data->depth-1)*4).'- '.$data->title;
        }
        $data->create = (int)substr($data->menu_auth, 0, 1);
        $data->read = (int)substr($data->menu_auth, 1, 1);
        $data->update = (int)substr($data->menu_auth, 2, 1);
        $data->delete = (int)substr($data->menu_auth, 3, 1);

        return parent::transformView($data); // TODO: Change the autogenerated stub
    }

    protected function beforeModify($key, $dto): array
    {
        $menuAuth = $this->Model->getData(['menu_auth'], [
            'where' => $this->idData,
        ]);

        switch (array_key_first($dto)) {
            case 'create' :
                $menuAuth = $dto[array_key_first($dto)].substr($menuAuth, 1, 3);
                break;
            case 'read' :
                $menuAuth = substr($menuAuth, 0, 1).$dto[array_key_first($dto)].substr($menuAuth, 2, 2);
                break;
            case 'update' :
                $menuAuth = substr($menuAuth, 0, 2).$dto[array_key_first($dto)].substr($menuAuth, 3, 1);
                break;
            case 'delete' :
                $menuAuth = substr($menuAuth, 0, 3).$dto[array_key_first($dto)];
                break;
        }

        $dto['menu_auth'] = $menuAuth;

        return parent::beforeModify($key, $dto); // TODO: Change the autogenerated stub
    }
}