<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class MenuList extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Model_Menu', 'Model');

        $this->setProperties($this->Model);

        if($this->flag !== 'admin') show_404();
    }

    public function caching_get()
    {
        $this->cachingMenu();

        $this->response(['code' => DATA_PROCESSED]);
    }

    public function generateMenuCode_get()
    {
        $menuList = $this->list([], false)['list'];

        $prefix = 'M';
        foreach ($menuList as $menu) {
            $code = $prefix.str_pad($menu->srt, 2, '0', STR_PAD_LEFT);
            $this->Model->modData([
                'code' => $code.'0000',
            ], [
                'menu_id' => $menu->menu_id,
            ]);

            if(count($menu->sub_menu)) {
                foreach ($menu->sub_menu as $subMenu) {
                    $subCode = $code.str_pad($subMenu->srt, 2, '0', STR_PAD_LEFT);
                    $this->Model->modData([
                        'code' => $subCode.'00',
                    ], [
                        'menu_id' => $subMenu->menu_id,
                    ]);
                }
            }
        }

        $this->cachingMenu();

        $this->response(['code' => DATA_PROCESSED]);
    }

    public function saveAll_post()
    {
        $data = $this->input->json();

        foreach ($data as $item) {
            $item['is_sub_menu'] = in_array($item['menu_id'], array_column($data, 'parent_id'));

            $params = [
                'parent_id' => $item['parent_id'],
                'depth' => $item['depth'],
                'srt' => $item['srt'],
                'is_sub_menu' => $item['is_sub_menu']?'1':'0',
            ];

            if($item['is_sub_menu']) {
                $params = array_merge($params, [
                    'class' => '',
                    'method' => '',
                ]);
            }

            $this->Model->modData($params, [
                'menu_id' => $item['menu_id'],
            ]);
        }

        $this->cachingMenu();

        $this->response(['code' => DATA_PROCESSED]);
    }

    protected function beforeList($data): array
    {
        $data['where']['depth'] = 1;
        $data['orderBy'] = ['srt' => 'asc'];
        return parent::beforeList($data); // TODO: Change the autogenerated stub
    }

    protected function executeList($data): array
    {
        $list = $this->Model->getList(
            $data['select'] ?? [],
            $data
        );

        foreach ($list as $item) {
            if($item->is_sub_menu) {
                $subList = $this->Model->getList([], [
                    'where' => [
                        'depth' => 2,
                        'parent_id' => $item->menu_id,
                    ],
                    'orderBy' => $data['orderBy'],
                ]);

                $item->sub_menu = $this->transformList($subList);
            }else{
                $item->sub_menu = [];
            }
        }

        $data['list'] = $this->transformList($list);

        return $data;
    }

    protected function transformView($data): object
    {
        $data->attr = @unserialize($data->attr);
        $data->params = @unserialize($data->params);
        $data->auth_params = @unserialize($data->auth_params);

        return parent::transformView($data);
    }

    protected function beforePost($key = 0, $model = null): array
    {
        list($key, $data) = parent::beforePost($key, $model); // TODO: Change the autogenerated stub

        if(empty($data['attr']['className'])) {
            $data['attr']['className'] = [];
        }else if(is_string($data['attr']['className'])){
            $data['attr']['className'] = explode(',', $data['attr']['className']);
        }

        foreach (['attr', 'params', 'auth_params'] as $field) {
            $data[$field] = serialize($data[$field]??[]);
        }

        return [$key, $data];
    }

    protected function afterModify($key, $dto)
    {
        $cnt = $this->Model->getCnt([
            'where' => [
                'parent_id' => $key,
            ],
        ]);

        if($cnt > 0) {
            $this->Model->modData([
                'is_login' => $dto['is_login'],
                'is_auth' => $dto['is_auth'],
                'is_super' => $dto['is_super'],
                'is_use' => $dto['is_use'],
            ], [
                'parent_id' => $key,
            ]);
        }
        parent::afterModify($key, $dto); // TODO: Change the autogenerated stub
    }

    protected function beforeResponse($data, $isFetch = false)
    {
        if(!$isFetch) $this->cachingMenu();
    }

    protected function cachingMenu()
    {
        $this->cache->file->delete('menu_done');

        $menuList = $this->deformMenuList($this->list([], false)['list']);

        $this->cache->file->save('menu_done', $menuList, 0);
    }
}