<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class Partners extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->routeTitle = '파트너';

        $this->validateModel('Model_User', 'Model_Parent');
        $this->validateModel('Model_Partner', 'Model');
        $this->validateModel('Model_Company');

        $this->setProperties($this->Model);

        $this->defaultList = [
            'user_cd' => 'USR002',
            'use_yn' => 'Y',
            'del_yn' => 'N',
            'approve_yn' => 'Y',
            'withdraw_yn' => 'N',
        ];
    }

    protected function transformView($data): object
    {
        if($this->mode === 'list') {
            if($data->company_ids) {
                $company_names = [];
                foreach (explode(',', $data->company_ids) as $company_id) {
                    $company_name = $this->Model_Company->getData(['company_name'], [
                        'where' => [
                            'company_id' => $company_id
                        ]
                    ]);
                    $company_names[] = $company_name;
                }
                $data->company_ids = implode(',', $company_names);
            }
        }
        return parent::transformView($data); // TODO: Change the autogenerated stub
    }

    protected function beforeAdd($dto, $model = null): array
    {
        parent::beforeAdd($dto, $model);
        $dto['user_api_key'] = generate_api_key();
        return $dto;
    }
}
