<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class PartnerAuth extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->routeTitle = '파트너 메뉴 권한';

        $this->load->model('Model_Partner_Auth', 'Model');
        $this->load->model('Model_Menu_Auth');
        $this->load->model('Model_Menu');
        $this->load->model('Model_Partner');

        $this->setProperties($this->Model);

        if($this->flag !== 'admin') show_404();
    }

    protected function beforeGet($key = 0, $strict = false): array
    {
        list($key, $data) = parent::beforeGet($key); // TODO: Change the autogenerated stub

        $partnerCnt = $this->Model_Partner->getCnt([
            'where' => [
                'user.del_yn' => 'N',
                'user.withdraw_yn' => 'N',
            ]
        ]);
        if(!$partnerCnt) {
            $this->response([
                'code' => BAD_REQUEST,
                'msg' => '메뉴 권한을 변경할 파트너가 존재하지 않습니다.'
            ]);
        }

        if(!isset($data['filter']['where']['partner_id'])) {
            $this->response([
                'code' => BAD_REQUEST,
                'msg' => '권한을 부여할 파트너가 지정되지 않았습니다.'
            ]);
        }

        $data['where'] = $data['filter']['where'];

        return [$key, $data];
    }

    protected function beforeList($data): array
    {
        $baseAuthList = $this->Model_Menu_Auth->getList([], [
            'where' => [
                'grade_cd' => 'USR002'
            ]
        ]);

        if(!count($baseAuthList) > 0) {
            $this->response([
                'code' => BAD_REQUEST,
                'msg' => '파트너 등급에 대한 메뉴별 기본 권한을 먼저 생성해주세요.'
            ]);
        }

        if(!$this->Model->getCnt($data)){
            $menuList = $this->Model_Menu_Auth->getList([], [
                'join' => [
                    'select' => 'title,code,depth,is_sub_menu,base_auth',
                    'table' => 'menu',
                    'matches' => [
                        'menu_id' => 'menu_id'
                    ],
                    'direction' => 'left'
                ],
                'where' => [
                    'grade_cd' => 'USR002',
                    'is_show' => 1,
                ],
                'orderBy' => [
                    'menu.depth' => 'asc',
                    'menu.parent_id' => 'asc',
                    'menu.srt' => 'asc',
                ]
            ]);

            foreach ($menuList as $item) {
                $this->Model->addData([
                    'partner_id' => $data['where']['partner_id'],
                    'menu_id' => $item->menu_id,
                    'is_show' => 1,
                    'menu_auth' => $item->menu_auth,
                    'scope_cd' => $item->scope_cd,
                ]);
            }
        }

        $data['join'] = [
            [
                'select' => 'title,code,depth,is_sub_menu',
                'table' => 'menu',
                'matches' => [
                    'menu_id' => 'menu_id'
                ],
                'direction' => 'left'
            ],
        ];

        $data['orderBy'] = [
            'menu.depth' => 'asc',
            'menu.parent_id' => 'asc',
            'menu.srt' => 'asc',
        ];

        return parent::beforeList($data);
    }

    protected function transformView($data): object
    {
        $data->title = lang('nav.'.$data->title);
        if($data->depth > 1) {
            $data->title = str_repeat('&nbsp;', ($data->depth-1)*4).'- '.$data->title;
        }
        $data->base_auth = $this->Model_Menu_Auth->getData(['menu_auth'], [
            'where' => [
                'menu_id' => $data->menu_id,
                'grade_cd' => 'USR002'
            ]
        ]);
        $data->create = (int)substr($data->menu_auth, 0, 1);
        $data->read = (int)substr($data->menu_auth, 1, 1);
        $data->update = (int)substr($data->menu_auth, 2, 1);
        $data->delete = (int)substr($data->menu_auth, 3, 1);
        $data->export = (int)substr($data->menu_auth, 4, 1);
        $data->import = (int)substr($data->menu_auth, 5, 1);
        $data->is_show = (int)$data->is_show;

        return parent::transformView($data); // TODO: Change the autogenerated stub
    }

    protected function executeList($data, $model = null): array
    {
        $data['orderBy'] = [
            'menu.depth' => 'asc',
            'menu.parent_id' => 'asc',
            'menu.srt' => 'asc',
        ];

        $list = [];
        $data['where']['menu.depth'] = 1;
        foreach ($this->Model->getList([], $data) as $menu) {
            $list[] = $menu;
            if((int)$menu->is_sub_menu) {
                $data['where']['menu.depth'] = 2;
                $data['where']['menu.parent_id'] = $menu->menu_id;
                foreach ($this->Model->getList([], $data) as $submenu) {
                    $list[] = $submenu;
                }
            }
        }

        $data['list'] = $this->transformList($list);

        return $data;
    }

    protected function beforeModify($key, $dto): array
    {
        $field = array_key_first($dto);

        if(in_array($field, ['create','read','update','delete','export','import'])) {
            $menuAuth = $this->Model->getData(['menu_auth'], [
                'where' => $this->idData,
            ]);
            $mode = $field;
            $value = $dto[$mode];
            $dto['menu_auth'] = modify_auth_char($mode, $menuAuth, $value);
        }else if($field === 'is_show') {
            if((int)$dto['is_show'] !== 1)  {
                $dto['menu_auth'] = BASE_AUTH_CHAR;
            }else{
                $dto['menu_auth'] = $this->Model_Menu_Auth->getData(['menu_auth'], [
                    'where' => [
                        'menu_id' => $this->idData['menu_id'],
                        'grade_cd' => 'USR002'
                    ]
                ]);
            }
        }

        return parent::beforeModify($key, $dto);
    }

    protected function executeModify($key, $dto, $bool, $model = null): array
    {
        $dto = $this->setData($dto, $model);
        $this->modData($dto, $this->idData, $bool, $model);
        return $dto;
    }

    protected function afterModify($key, $dto)
    {
        $subMenuList = $this->Model_Menu->getList([], [
            'where' => ['parent_id' => $this->idData['menu_id'],]
        ]);
        if(count($subMenuList)) {
            foreach ($subMenuList as $subMenuData) {
                $this->Model->modData($dto, array_merge($this->idData,['menu_id' => $subMenuData->menu_id]));
            }
        }
        parent::afterModify($key, $dto);
    }

    public function reset_get()
    {
        $this->Model->truncate();
        $this->response(['code' => DATA_PROCESSED]);
    }
}
