<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class SysCode extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Model_Sys_Code', 'Model');

        $this->setProperties($this->Model);

        if($this->flag !== 'admin') show_404();
    }

    protected function beforeList($data): array
    {
        $this->db->where_not_in('sml_cd', ['000']);
        return $data;
    }

    protected function executeAdd($dto, $bool): array
    {
        if($dto['sml_cd'] !== '000') {
            $this->reorderCodeList($dto['big_cd'], $dto);
            return $dto;
        }else{
            return parent::executeAdd($dto, $bool);
        }
    }

    protected function executeModify($key, $dto, $bool): array
    {
        if($dto['sml_cd'] !== '000') {
            $list = $this->Model->getList([], [
                'where' => ['big_cd' => $dto['big_cd']],
                'whereNot' => ['cmb_cd' => $dto['cmb_cd']],
            ]);
            $this->reorderCodeList($dto['big_cd'], $dto, $list);
            return $dto;
        }else{
            return parent::executeModify($key, $dto, $bool); // TODO: Change the autogenerated stub
        }
    }

    protected function beforeRemove($key = 0, $data = []): array
    {
        if(substr($key, 3) === '000') {
            $bigCd = substr($key, 0, 3);
            if ($this->Model->getCntWhere(['big_cd' => $bigCd,]) > 1) {
                $this->response(['code' => BAD_REQUEST, 'msg' => 'You Should Delete Codes In The Category']);
            }
        }

        return parent::beforeRemove($key, $data);
    }

    protected function afterRemove($key, $data = [])
    {
        $bigCd = substr($key, 0, 3);
        if ($this->Model->getCntWhere(['big_cd' => $bigCd,]) > 1) {
            $this->reorderCodeList($bigCd);
        }

        parent::afterRemove($key, $data);
    }
}