<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class SysCode extends Common
{
    protected string $bigCd;
    protected string $smlCd;

    function __construct()
    {
        parent::__construct();

        $this->routeTitle = '시스템 코드';

        $this->validateModel('Model_Sys_Code', 'Model');

        $this->setProperties($this->Model);

        if($this->flag !== 'admin') show_404();
    }

    protected function beforeList($data): array
    {
        $data['whereNot'] = ['sml_cd' => '000'];
        $data = parent::beforeList($data);
        return $data;
    }

    protected function executeAdd($dto, $bool, $model = null): array
    {
        if($dto['sml_cd'] === '000') {
            return parent::executeAdd($dto, $bool);
        }else{
            $dto = parent::executeAdd($dto, $bool, $model);
            $this->reorderList('cd_srt', 'cmb_cd', 'big_cd', [
                'whereNot' => ['sml_cd' => '000']
            ], $dto);
            return $dto;
        }
    }

    protected function executeModify($key, $dto, $bool, $model = null): array
    {
        if($dto['sml_cd'] === '000') {
            return parent::executeModify($key, $dto, $bool); // TODO: Change the autogenerated stub
        }else{
            $original = $this->Model->getData([], [
                'where' => ['cmb_cd' => $dto['cmb_cd']],
            ]);

            if(!array_key_exists('cd_srt', $dto) || (int)$dto['cd_srt'] === (int)$original->category_srt) {
                return parent::executeModify($key, $dto, $bool, $model); // TODO: Change the autogenerated stub
            }else{
                $dto = parent::executeModify($key, $dto, $bool, $model);
                $this->reorderList('cd_srt', 'cmb_cd', 'big_cd', [
                    'whereNot' => ['sml_cd' => '000']
                ], $dto);
                return $dto;
            }
        }
    }

    protected function beforeRemove($key = 0, $data = []): array
    {
        $this->smlCd = substr($key, 3);

        if($this->smlCd === '000') {
            $this->bigCd = substr($key, 0, 3);
            if ($this->Model->getCntWhere(['big_cd' => $this->bigCd,]) > 1) {
                $this->response(['code' => BAD_REQUEST, 'msg' => 'You Should Delete Codes In The Category']);
            }
        }

        return parent::beforeRemove($key, $data);
    }

    protected function executeRemove($key, $data, $bool): array
    {
        $data = parent::executeRemove($key, $data, $bool);

        if($this->smlCd !== '000') {
            $this->reorderList('cd_srt', 'cmb_cd', 'big_cd', [
                'where' => ['big_cd' => $this->bigCd],
                'whereNot' => ['sml_cd' => '000']
            ]);
        }

        return $data;
    }
}
