<?php
defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class Visitors extends Common
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Model_Visitor', 'Model');

        $this->setProperties($this->Model);
    }

    protected function transformView($data): object
    {
        $data->vi_datetime = $data->vi_date . '<br>' . $data->vi_time;

        if($data->vi_referrer) {
            $baseUrlParsed = parse_url(base_url());
            $referrerParsed = parse_url($data->vi_referrer);
            if($baseUrlParsed['host'] === $referrerParsed['host']) {
                $data->vi_referrer = '-';
            }
        }else{
            $data->vi_referrer = '-';
        }

        return parent::transformView($data); // TODO: Change the autogenerated stub
    }
}
