<?php
defined('BASEPATH') OR exit('No direct script access allowed');

define("BUILDER_ASSET_URI", 'public/assets/' . basename(__DIR__) . '/');

const BUILDER_FLAGNAME = 'builder';
const BUILDER_ASSET_PATH = FCPATH . BUILDER_ASSET_URI;

const BUILDER_ASSET_AUDIO_URI = BUILDER_ASSET_URI . 'audio/';
const BUILDER_ASSET_AUDIO_PATH = FCPATH . BUILDER_ASSET_AUDIO_URI;

const BUILDER_ASSET_CSS_URI = BUILDER_ASSET_URI . 'css/';
const BUILDER_ASSET_CSS_PATH = FCPATH . BUILDER_ASSET_CSS_URI;

const BUILDER_ASSET_IMG_URI = BUILDER_ASSET_URI . 'img/';
const BUILDER_ASSET_IMG_PATH = FCPATH . BUILDER_ASSET_IMG_URI;

const BUILDER_ASSET_JS_URI = BUILDER_ASSET_URI . 'js/';
const BUILDER_ASSET_JS_PATH = FCPATH . BUILDER_ASSET_JS_URI;

const BUILDER_ASSET_JSON_URI = BUILDER_ASSET_URI . 'json/';
const BUILDER_ASSET_JSON_PATH = FCPATH . BUILDER_ASSET_JSON_URI;

const BUILDER_ASSET_SVG_URI = BUILDER_ASSET_URI . 'svg/';
const BUILDER_ASSET_SVG_PATH = FCPATH . BUILDER_ASSET_SVG_URI;

const BUILDER_ASSET_VENDOR_URI = BUILDER_ASSET_URI . 'vendor/';
const BUILDER_ASSET_VENDOR_PATH = FCPATH . BUILDER_ASSET_VENDOR_URI;
