<?php
$config['web_form_config_loaded'] = true;

$config['form_login_config'] = [
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'text',
		'icon' => 'ri-user-line',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
	],
];

$config['form_find_id_config'] = [
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'category' => 'basic',
		'type' => 'email',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User Email',
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];

$config['form_find_password_config'] = [
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required',
		'category' => 'basic',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required',
		'category' => 'basic',
		'type' => 'email',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User Email',
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];

$config['form_password_check_config'] = [
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
	],
];

$config['form_signup_config'] = [
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'USR002',
		'list' => false,
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
		'form' => true,
		'errors' => [],
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-user-line',
		'form_text' => 'Please enter at least 4 characters',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"id", "title":"아이디"}',
			'text_type' => 'eng|num',
		],
		'list' => true,
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]|strong_password',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'icon' => 'svg:ri-lock-password-line',
		'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'envelope_name' => false,
			'label' => 'lang:user.password',
			'form_text' => '',
			'type' => 'new_password',
			'key' => 'password',
		],
		'list' => false,
	],
	[
		'field' => 'password_confirm',
		'label' => 'lang:user.password_confirm',
		'rules' => 'trim|required_mod[add]|password_matches[password]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'subtype' => 'password_confirm',
		'icon' => 'svg:ri-lock-password-fill',
		'form_text' => 'Please Repeat The Password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'key' => 'password_confirm',
		],
		'list' => false,
	],
	[
		'field' => 'name',
		'label' => 'lang:user.name',
		'rules' => 'trim|required',
		'form' => true,
		'list' => true,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'form' => true,
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-font-family',
		'attributes' => [
			'placeholder' => 'Enter The User Email',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"email", "title":"이메일"}',
			'text_type' => 'email',
		],
		'list' => true,
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'code',
		'label' => 'lang:student.code',
		'form' => true,
		'rules' => 'trim|required|exact_length[8]|integer|is_unique[student.code.student_id]',
		'errors' => [],
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-number-2',
		'form_text' => 'Enter The Student Code',
		'attributes' => [],
		'form_attributes' => [
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"code", "title":"학번"}',
			'text_type' => 'num',
		],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'grade',
		'label' => 'lang:student.grade',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'select',
		'subtype' => 'selectpicker',
		'attributes' => [
			'placeholder' => 'Select The Grade',
		],
		'option_attributes' => [
			'option_type' => 'field',
		],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'disabilities_yn',
		'label' => 'lang:student.disabilities_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
        'type' => 'checkbox',
        'subtype' => 'single',
        'option_attributes' => [
            'option_type' => 'static',
            'option_data' => [
                'Y' => 'lang:student.disabilities_yn',
            ],
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'aac_yn',
		'label' => 'lang:student.aac_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
        'type' => 'checkbox',
        'subtype' => 'single',
        'option_attributes' => [
            'option_type' => 'static',
            'option_data' => [
                'Y' => 'lang:student.aac_yn',
            ],
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];

$config['form_works_config'] = [
	[
		'field' => 'article_id',
		'label' => 'lang:article.article_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'board_id',
		'label' => 'lang:board.board_id',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'hidden',
		'default' => 3,
		'list' => false,
	],
	[
		'field' => 'open_yn',
		'label' => 'lang:article.open_yn',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'hidden',
		'default' => 'N',
		'list' => false,
	],
	[
		'field' => 'subject',
		'label' => 'lang:article.subject',
		'form' => true,
		'rules' => 'trim|required|max_length[300]',
		'errors' => [],
		'type' => 'text',
		'attributes' => [],
		'list' => true,
	],
	[
		'field' => 'content',
		'label' => 'lang:article.content',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'textarea',
		'attributes' => [],
		'list' => false,
	],
	[
		'field' => 'thumbnail',
		'label' => 'lang:epmagazine.thumbnail',
		'form' => true,
		'rules' => 'trim|dropzone_required',
		'errors' => [],
		'category' => 'custom',
		'type' => 'file',
		'subtype' => 'dropzone-full',
		'icon' => 'ri-file-image-line',
		'form_text' => [
			'line' => 'Drop files here or click to upload',
			'replace' => 'IMG',
			'icon' => 'ri-file-image-fill',
			'icon_size' => 16,
		],
		'attributes' => [
			'max' => 1,
			'accept' => 'image/jpeg,image/png',
			'multiple' => 'false',
		],
		'form_attributes' => [
			'with_list' => true,
			'list_delete' => 'thumbnail',
		],
		'list' => true,
		'list_attributes' => [
		]
	],
];

$config['form_notices_config'] = [
	[
		'field' => 'article_id',
		'label' => 'lang:article.article_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'board_id',
		'label' => 'lang:board.board_id',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'hidden',
		'default' => 3,
		'list' => false,
	],
	[
		'field' => 'open_yn',
		'label' => 'lang:article.open_yn',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'hidden',
		'default' => 'Y',
		'list' => false,
	],
	[
		'field' => 'subject',
		'label' => 'lang:article.subject',
		'form' => true,
		'rules' => 'trim|required|max_length[300]',
		'errors' => [],
		'type' => 'text',
		'attributes' => [],
		'list' => true,
	],
	[
		'field' => 'content',
		'label' => 'lang:article.content',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'textarea',
		'attributes' => [],
		'list' => false,
	],
	[
		'field' => 'uploads',
		'label' => 'lang:article.uploads',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'file',
		'icon' => 'ri-file-image-line',
		'attributes' => [
			'accept' => 'image/jpeg,image/png',
		],
		'form_text' => [
			'line' => 'Upload File Only',
			'replace' => 'IMG',
			'icon' => 'ri-file-image-fill',
			'icon_size' => 16,
		],
		'form_attributes' => [
			'with_list' => true,
			'list_sorter' => true,
			'list_delete' => 'attachment',
		],
		'list' => false,
	],
];

$config['form_inquiries_config'] = [
	[
		'field' => 'article_id',
		'label' => 'lang:article.article_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'board_id',
		'label' => 'lang:board.board_id',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'hidden',
		'default' => 2,
		'list' => false,
	],
	[
		'field' => 'open_yn',
		'label' => 'lang:article.open_yn',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'hidden',
		'default' => 'Y',
		'list' => false,
	],
	[
		'field' => 'subject',
		'label' => 'lang:article.subject',
		'form' => true,
		'rules' => 'trim|required|max_length[300]',
		'errors' => [],
		'type' => 'text',
		'attributes' => [],
		'list' => true,
	],
	[
		'field' => 'content',
		'label' => 'lang:article.content',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'textarea',
		'attributes' => [],
		'list' => false,
	],
];

$config['form_myinfo_config'] = [
	[
		'field' => 'student_id',
		'label' => 'lang:student.student_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'errors' => [],
		'type' => 'hidden',
		'subtype' => 'identifier',
	],
	[
		'field' => 'user_id',
		'label' => 'lang:user.user_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'errors' => [],
		'type' => 'hidden',
	],
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'type' => 'hidden',
		'default' => 'USR002',
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
		'form' => true,
		'errors' => [],
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-user-line',
		'form_text' => 'Please enter at least 4 characters',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => '아이디를 입력하세요',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => false,
		],
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]|strong_password',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'icon' => 'svg:ri-lock-password-line',
		'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'envelope_name' => false,
			'label' => 'lang:user.password',
			'form_text' => '',
			'type' => 'new_password',
			'key' => 'password',
		],
	],
	[
		'field' => 'password_confirm',
		'label' => 'lang:user.password_confirm',
		'rules' => 'trim|required_mod[add]|password_matches[password]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'subtype' => 'password_confirm',
		'icon' => 'svg:ri-lock-password-fill',
		'form_text' => 'Please Repeat The Password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'key' => 'password_confirm',
		],
	],
	[
		'field' => 'name',
		'label' => 'lang:user.name',
		'rules' => 'trim|required',
		'form' => true,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'form' => true,
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-font-family',
		'attributes' => [
			'placeholder' => 'Enter The User Email',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => false,
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list_attributes' => [],
	],
	[
		'field' => 'code',
		'label' => 'lang:student.code',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'subtype' => 'readonly',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list_attributes' => [],
	],
	[
		'field' => 'grade',
		'label' => 'lang:student.grade',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'type' => 'select',
		'subtype' => 'selectpicker',
		'attributes' => [
			'placeholder' => 'Select The Grade',
		],
		'option_attributes' => [
			'option_type' => 'field',
		],
		'default' => '',
		'list_attributes' => [],
	],
	[
		'field' => 'disabilities_yn',
		'label' => 'lang:student.disabilities_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'type' => 'checkbox',
		'subtype' => 'single',
		'option_attributes' => [
			'option_type' => 'static',
			'option_data' => [
				'Y' => 'lang:student.disabilities_yn',
			],
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'default' => '',
		'list_attributes' => [],
	],
	[
		'field' => 'aac_yn',
		'label' => 'lang:student.aac_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'type' => 'checkbox',
		'subtype' => 'single',
		'option_attributes' => [
			'option_type' => 'static',
			'option_data' => [
				'Y' => 'lang:student.aac_yn',
			],
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'default' => '',
		'list_attributes' => [],
	],
];
