<?php
defined('BASEPATH') OR exit('No direct script access allowed');

define('PLATFORM_NAME', basename(__DIR__));
const PLATFORM_ASSET_URI = 'public/assets/'.PLATFORM_NAME.DIRECTORY_SEPARATOR;
const PLATFORM_ASSET_PATH = FCPATH . PLATFORM_ASSET_URI;

const PLATFORM_ASSET_AUDIO_URI = PLATFORM_ASSET_URI . 'audio/';
const PLATFORM_ASSET_AUDIO_PATH = FCPATH . PLATFORM_ASSET_AUDIO_URI;

const PLATFORM_ASSET_CSS_URI = PLATFORM_ASSET_URI . 'css/';
const PLATFORM_ASSET_CSS_PATH = FCPATH . PLATFORM_ASSET_CSS_URI;

const PLATFORM_ASSET_IMG_URI = PLATFORM_ASSET_URI . 'img/';
const PLATFORM_ASSET_IMG_PATH = FCPATH . PLATFORM_ASSET_IMG_URI;

const PLATFORM_ASSET_JS_URI = PLATFORM_ASSET_URI . 'js/';
const PLATFORM_ASSET_JS_PATH = FCPATH . PLATFORM_ASSET_JS_URI;

const PLATFORM_ASSET_JSON_URI = PLATFORM_ASSET_URI . 'json/';
const PLATFORM_ASSET_JSON_PATH = FCPATH . PLATFORM_ASSET_JSON_URI;

const PLATFORM_ASSET_SVG_URI = PLATFORM_ASSET_URI . 'svg/';
const PLATFORM_ASSET_SVG_PATH = FCPATH . PLATFORM_ASSET_SVG_URI;

const PLATFORM_ASSET_VENDOR_URI = PLATFORM_ASSET_URI . 'vendor/';
const PLATFORM_ASSET_VENDOR_PATH = FCPATH . PLATFORM_ASSET_VENDOR_URI;

const APP_AOS_URL = '';
const APP_IOS_URL = '';
