<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Common extends MY_Builder_WEB
{
    public array $navAuth = [];
    public bool $containerFluid = false;
    public bool $hideLogoAtLogin = true;

    public function __construct()
    {
        $this->flag = 'admin';
        $this->apiFlag = 'api';

        parent::__construct();

        $this->navAuth = [];
        $this->defaultController = $this->config->get('platform_config.loggedInRedirect', 'dashboard');

        $this->addCSS[] = base_url('public/assets/admin/css/style.css');

        if(!(int)getenv('IS_ADMIN')) show_404();
    }

    protected function checkLoggedIn()
    {
        parent::checkLoggedIn();

        if($this->isLoggedIn){
            $valid = true;
            $userCd = $this->sessionData['user_cd'] ?? null;
            if(!in_array($userCd, ['USR000','USR001','USR002'])) $valid = false;

            if(!$valid) {
                $this->destroyUserData();
                redirect(base_url($this->noLoginRedirect));
            }

            $this->isAdmin = true;
            $this->headerData = [
                'id' => $this->sessionData['id'],
                'user_id' => $this->sessionData['user_id'],
                'name' => $this->sessionData['name'],
                'user_cd' => $this->sessionData['user_cd'],
            ];
        }
    }

    protected function viewApp($data = [])
    {
        $data['isSystemAdmin'] = $this->isSystemAdmin;
        $data['containerFluid'] = $this->containerFluid;
        $data['hideLogoAtLogin'] = $this->hideLogoAtLogin;

        parent::viewApp($data); // TODO: Change the autogenerated stub
    }
}
