<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Common extends MY_Builder_WEB
{
    public bool $isSystemAdmin = false;

    public function __construct()
    {
        $this->flag = 'admin';
        $this->apiFlag = 'api';

        parent::__construct();

        $this->load->model('Model_User');
        $this->load->model('Model_Menu');
        $this->load->model('Model_Menu_Auth');

        $this->navAuth = [];
        $this->defaultController = $this->config->get('platform_config.isLoginRedirect', 'dashboard');

        $this->addCSS[] = base_url('public/assets/admin/css/style.css');

        if(!(int)getenv('IS_ADMIN')) show_404();
    }

    protected function checkLogin(): bool
    {
        if(parent::checkLogin()){
            $valid = true;
            if(!property_exists($this->loginData, 'user_cd')) $valid = false;
            $user = $this->Model_User->getDataWhere([], ['user_id' => $this->session->userdata('user_id')]);
            if(!$user || !in_array($user->user_cd, ['USR000','USR001'])) $valid = false;

            if(!$valid) {
                $this->destroyUserData();
                redirect(base_url($this->noLoginRedirect));
            }

            $this->isAdmin = true;
            $this->userData = (array)$user;
            $this->headerData = [
                'id' => $user->id,
                'user_id' => $user->user_id,
                'name' => $user->name,
                'user_cd' => $user->user_cd,
            ];
            if($user->user_cd === 'USR000') $this->isSystemAdmin = true;

            return true;
        }else{
            return false;
        }
    }

    protected function viewApp($data = [])
    {
        $data['isSystemAdmin'] = $this->isSystemAdmin;
        $data['containerFluid'] = false;

        parent::viewApp($data); // TODO: Change the autogenerated stub
    }

    protected function setMenuList(): array
    {
        $menuList = parent::setMenuList();

        if($this->isLogin) {
            if($this->userData['user_cd'] !== 'USR000') {
                $authList = $this->Model_Menu_Auth->getList([], [
                    'where' => [
                        'user_cd' => $this->userData['user_cd'],
                        'is_show' => 1,
                    ],
                ]);

                $menuIdList = array_column($authList, 'menu_id');
                $menuList = array_filter($menuList, function ($item) use ($menuIdList) {
                    return in_array($item['menuId'], $menuIdList);
                });
            }
        }

        return $menuList;
    }
}
